import { Horizon, Networks } from '@stellar/stellar-sdk';

const NETWORK = process.env.STELLAR_NETWORK || 'testnet';
const HORIZON_URL =
  NETWORK === 'mainnet'
    ? 'https://horizon.stellar.org'
    : 'https://horizon-testnet.stellar.org';

const SOROBAN_RPC_URL =
  NETWORK === 'mainnet'
    ? 'https://mainnet.sorobanrpc.com'
    : 'https://soroban-testnet.stellar.org';

const NETWORK_PASSPHRASE =
  NETWORK === 'mainnet' ? Networks.PUBLIC : Networks.TESTNET;

export const stellarConfig = {
  network: NETWORK,
  horizonUrl: HORIZON_URL,
  sorobanRpcUrl: SOROBAN_RPC_URL,
  networkPassphrase: NETWORK_PASSPHRASE,
};

export function getHorizonServer(): Horizon.Server {
  return new Horizon.Server(HORIZON_URL);
}

export const CONTRACT_IDS = {
  AD_REGISTRY: process.env.CONTRACT_AD_REGISTRY || '',
  CAMPAIGN_ORCHESTRATOR: process.env.CONTRACT_CAMPAIGN_ORCHESTRATOR || '',
  ESCROW_VAULT: process.env.CONTRACT_ESCROW_VAULT || '',
  FRAUD_PREVENTION: process.env.CONTRACT_FRAUD_PREVENTION || '',
  PAYMENT_PROCESSOR: process.env.CONTRACT_PAYMENT_PROCESSOR || '',
  GOVERNANCE_TOKEN: process.env.CONTRACT_GOVERNANCE_TOKEN || '',
  GOVERNANCE_DAO: process.env.CONTRACT_GOVERNANCE_DAO || '',
  PUBLISHER_VERIFICATION: process.env.CONTRACT_PUBLISHER_VERIFICATION || '',
  PUBLISHER_REPUTATION: process.env.CONTRACT_PUBLISHER_REPUTATION || '',
  ANALYTICS_AGGREGATOR: process.env.CONTRACT_ANALYTICS_AGGREGATOR || '',
  AUCTION_ENGINE: process.env.CONTRACT_AUCTION_ENGINE || '',
  SUBSCRIPTION_MANAGER: process.env.CONTRACT_SUBSCRIPTION_MANAGER || '',
  PRIVACY_LAYER: process.env.CONTRACT_PRIVACY_LAYER || '',
  TARGETING_ENGINE: process.env.CONTRACT_TARGETING_ENGINE || '',
  DISPUTE_RESOLUTION: process.env.CONTRACT_DISPUTE_RESOLUTION || '',
  REVENUE_SETTLEMENT: process.env.CONTRACT_REVENUE_SETTLEMENT || '',
  REWARDS_DISTRIBUTOR: process.env.CONTRACT_REWARDS_DISTRIBUTOR || '',
  // Missing contracts added below
  GOVERNANCE_CORE: process.env.CONTRACT_GOVERNANCE_CORE || '',
  TIMELOCK_EXECUTOR: process.env.CONTRACT_TIMELOCK_EXECUTOR || '',
  PUBLISHER_NETWORK: process.env.CONTRACT_PUBLISHER_NETWORK || '',
  CAMPAIGN_ANALYTICS: process.env.CONTRACT_CAMPAIGN_ANALYTICS || '',
  CAMPAIGN_LIFECYCLE: process.env.CONTRACT_CAMPAIGN_LIFECYCLE || '',
  AUDIENCE_SEGMENTS: process.env.CONTRACT_AUDIENCE_SEGMENTS || '',
  IDENTITY_REGISTRY: process.env.CONTRACT_IDENTITY_REGISTRY || '',
  KYC_REGISTRY: process.env.CONTRACT_KYC_REGISTRY || '',
  CREATIVE_MARKETPLACE: process.env.CONTRACT_CREATIVE_MARKETPLACE || '',
  SUBSCRIPTION_BENEFITS: process.env.CONTRACT_SUBSCRIPTION_BENEFITS || '',
  LIQUIDITY_POOL: process.env.CONTRACT_LIQUIDITY_POOL || '',
  MILESTONE_TRACKER: process.env.CONTRACT_MILESTONE_TRACKER || '',
  MULTISIG_TREASURY: process.env.CONTRACT_MULTISIG_TREASURY || '',
  ORACLE_INTEGRATION: process.env.CONTRACT_ORACLE_INTEGRATION || '',
  PAYOUT_AUTOMATION: process.env.CONTRACT_PAYOUT_AUTOMATION || '',
  PERFORMANCE_ORACLE: process.env.CONTRACT_PERFORMANCE_ORACLE || '',
  RECURRING_PAYMENT: process.env.CONTRACT_RECURRING_PAYMENT || '',
  REFUND_PROCESSOR: process.env.CONTRACT_REFUND_PROCESSOR || '',
  TOKEN_BRIDGE: process.env.CONTRACT_TOKEN_BRIDGE || '',
  WRAPPED_TOKEN: process.env.CONTRACT_WRAPPED_TOKEN || '',
  BUDGET_OPTIMIZER: process.env.CONTRACT_BUDGET_OPTIMIZER || '',
  ANOMALY_DETECTOR: process.env.CONTRACT_ANOMALY_DETECTOR || '',
};
