export interface SecurityHeader {
  key: string;
  value: string;
}

interface SecurityHeaderOptions {
  /** Origin of the WebSocket server, e.g. `wss://api.example.com`. */
  wsUrl?: string | undefined;
  /** When true the CSP is enforced; otherwise it is sent as report-only. */
  enforceCsp?: boolean;
  /** Next.js dev needs `unsafe-eval` for hot reloading. */
  isDev?: boolean;
  /** Per-request nonce for inline scripts (generated by middleware). */
  nonce?: string;
  /** CSP reporting endpoint URL (e.g. `/api/csp-report` or a Sentry URL). */
  reportTo?: string;
}

function originOf(url: string | undefined): string | null {
  if (!url) return null;
  try {
    return new URL(url).origin;
  } catch {
    return null;
  }
}

/**
 * Builds the Content-Security-Policy for the app. Only the origins the app
 * needs are allowed: itself, its WebSocket server, the Stellar RPC/Horizon
 * endpoints, the backend API, and Sentry.
 *
 * When a `nonce` is provided (from middleware), `'unsafe-inline'` is dropped
 * from `script-src` in favour of `'nonce-{value}'`, which blocks injected
 * inline scripts while allowing Next.js bootstrap scripts that carry the
 * matching nonce.
 */
export function buildCsp({ wsUrl, isDev = false, nonce, reportTo }: SecurityHeaderOptions = {}): string {
  const scriptSrc = ["'self'"];
  if (nonce) {
    scriptSrc.push(`'nonce-${nonce}'`);
  } else {
    // Fallback when no nonce is available (e.g. build-time evaluation).
    scriptSrc.push("'unsafe-inline'");
  }
  if (isDev) {
    scriptSrc.push("'unsafe-eval'");
  }

  const connectSrc = [
    "'self'",
    originOf(wsUrl),
    // Backend API — runs on a separate origin in production
    process.env.NEXT_PUBLIC_API_URL && originOf(process.env.NEXT_PUBLIC_API_URL),
    "https://*.stellar.org",
    "https://*.sentry.io",
  ].filter((value): value is string => Boolean(value));

  const directives: Record<string, string[]> = {
    "default-src": ["'self'"],
    "script-src": scriptSrc,
    "style-src": ["'self'", "'unsafe-inline'"],
    "img-src": ["'self'", "data:", "blob:", "https:"],
    "font-src": ["'self'", "data:"],
    "connect-src": connectSrc,
    "frame-ancestors": ["'none'"],
    "base-uri": ["'self'"],
    "form-action": ["'self'"],
    "object-src": ["'none'"],
  };

  if (reportTo) {
    directives["report-uri"] = [reportTo];
  }

  return Object.entries(directives)
    .map(([name, values]) => `${name} ${values.join(" ")}`)
    .join("; ");
}

/**
 * Security headers for every route. The CSP ships as report-only unless
 * `enforceCsp` is set, so violations can be observed before it is enforced;
 * clickjacking protection (`X-Frame-Options`) is enforced either way because
 * `frame-ancestors` is ignored in report-only mode.
 *
 * In production, these are set by middleware.ts (which can generate a
 * per-request nonce). This function is retained for build-time fallbacks
 * and testing.
 */
export function buildSecurityHeaders(options: SecurityHeaderOptions = {}): SecurityHeader[] {
  return [
    {
      key: options.enforceCsp
        ? "Content-Security-Policy"
        : "Content-Security-Policy-Report-Only",
      value: buildCsp(options),
    },
    { key: "X-Frame-Options", value: "DENY" },
    { key: "X-Content-Type-Options", value: "nosniff" },
    { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
    {
      key: "Permissions-Policy",
      value: "camera=(), microphone=(), geolocation=()",
    },
    {
      key: "Strict-Transport-Security",
      value: "max-age=63072000; includeSubDomains",
    },
  ];
}
